export interface LearningModule {
  id: string
  slug: string
  title: string
  category: "Offensive" | "Defensive" | "AI Security" | "Forensics" | "Foundations"
  difficulty: "Easy" | "Medium" | "Hard"
  roomCount: number
  estimatedTime: string
  description: string
  iconType: "forensics" | "devsecops" | "exploit" | "soc" | "injection" | "networking" | "crypto" | "deepfake" | "malware" | "cloud" | "phishing" | "hunting"
  badgeColor: {
    bg: string
    border: string
    iconColor: string
    glow: string
  }
  skills: string[]
  completedPercentage?: number
}

export const learningModules: LearningModule[] = [
  {
    id: "mod-1",
    slug: "digital-forensics-and-incident-response",
    title: "Digital Forensics and Incident Response",
    category: "Forensics",
    difficulty: "Medium",
    roomCount: 6,
    estimatedTime: "5 hours",
    description: "Forensic artifacts are pieces of evidence left by human activity. In this module, we will learn about the artifacts found on Windows, memory forensics, and how to reconstruct cyber incident timelines.",
    iconType: "forensics",
    badgeColor: {
      bg: "bg-blue-950/40",
      border: "border-blue-500/30",
      iconColor: "text-blue-400",
      glow: "from-blue-600/20 to-cyan-500/10",
    },
    skills: ["Memory Analysis", "Event Log Forensics", "Timeline Reconstruction", "Volatility"],
    completedPercentage: 65,
  },
  {
    id: "mod-2",
    slug: "prompt-injection-and-llm-attacks",
    title: "Prompt Injection & LLM Exploits",
    category: "AI Security",
    difficulty: "Hard",
    roomCount: 5,
    estimatedTime: "4 hours",
    description: "Learn how attackers bypass LLM safety guardrails using direct and indirect prompt injection, jailbreaking tokens, data extraction, and weaponized AI prompt engineering.",
    iconType: "injection",
    badgeColor: {
      bg: "bg-red-950/40",
      border: "border-red-500/30",
      iconColor: "text-red-400",
      glow: "from-red-600/20 to-rose-500/10",
    },
    skills: ["Jailbreaking", "System Prompt Leakage", "Indirect Injection", "Safety Guardrails"],
    completedPercentage: 20,
  },
  {
    id: "mod-3",
    slug: "secure-software-development",
    title: "Secure Software Development",
    category: "Foundations",
    difficulty: "Easy",
    roomCount: 4,
    estimatedTime: "3.5 hours",
    description: "In this module, we learn about DevSecOps, a philosophy that emphasizes integrating security practices throughout the entire software development lifecycle, SAST/DAST pipelines, and secret management.",
    iconType: "devsecops",
    badgeColor: {
      bg: "bg-emerald-950/40",
      border: "border-emerald-500/30",
      iconColor: "text-emerald-400",
      glow: "from-emerald-600/20 to-teal-500/10",
    },
    skills: ["DevSecOps", "SAST / DAST", "CI/CD Security", "Secret Hygiene"],
    completedPercentage: 100,
  },
  {
    id: "mod-4",
    slug: "attacks-and-exploits",
    title: "Attacks and Exploits",
    category: "Offensive",
    difficulty: "Medium",
    roomCount: 7,
    estimatedTime: "6 hours",
    description: "This module starts by introducing the most common vulnerabilities in web applications. Then it explains MS Windows privilege escalation, lateral movement, and post-exploitation workflows.",
    iconType: "exploit",
    badgeColor: {
      bg: "bg-rose-950/40",
      border: "border-rose-500/30",
      iconColor: "text-rose-400",
      glow: "from-rose-600/20 to-red-500/10",
    },
    skills: ["Privilege Escalation", "Web Exploitation", "Metasploit", "Post-Exploitation"],
    completedPercentage: 0,
  },
  {
    id: "mod-5",
    slug: "soc-level-1-capstone-challenges",
    title: "SOC Level 1 Capstone Challenges",
    category: "Defensive",
    difficulty: "Medium",
    roomCount: 8,
    estimatedTime: "7 hours",
    description: "In this module, you will handle real-world incidents composed of different Tactics, Techniques, and Procedures (TTPs), starting from initial access to data exfiltration and MITRE ATT&CK mapping.",
    iconType: "soc",
    badgeColor: {
      bg: "bg-cyan-950/40",
      border: "border-cyan-500/30",
      iconColor: "text-cyan-400",
      glow: "from-cyan-600/20 to-blue-500/10",
    },
    skills: ["SIEM Alert Triage", "MITRE ATT&CK", "Incident Playbooks", "Log Correlation"],
    completedPercentage: 40,
  },
  {
    id: "mod-6",
    slug: "deepfake-and-voice-cloning-defense",
    title: "Deepfake & Voice Cloning Defense",
    category: "AI Security",
    difficulty: "Medium",
    roomCount: 4,
    estimatedTime: "3 hours",
    description: "Understand how synthetic voice cloning and video generative AI are weaponized for executive impersonation (CEO Fraud), social engineering, and live meeting video manipulation.",
    iconType: "deepfake",
    badgeColor: {
      bg: "bg-amber-950/40",
      border: "border-amber-500/30",
      iconColor: "text-amber-400",
      glow: "from-amber-600/20 to-yellow-500/10",
    },
    skills: ["Voice Cloning Detection", "Video Artifact Analysis", "Multi-Channel Verification", "BEC Defense"],
    completedPercentage: 0,
  },
  {
    id: "mod-7",
    slug: "ai-driven-phishing-and-social-engineering",
    title: "AI-Driven Phishing & Social Engineering",
    category: "AI Security",
    difficulty: "Easy",
    roomCount: 5,
    estimatedTime: "4 hours",
    description: "Learn how modern adversaries leverage LLMs to automate personalized spear-phishing campaigns at scale, bypass spam filters, craft deceptive lures, and how users can spot red flags.",
    iconType: "phishing",
    badgeColor: {
      bg: "bg-purple-950/40",
      border: "border-purple-500/30",
      iconColor: "text-purple-400",
      glow: "from-purple-600/20 to-indigo-500/10",
    },
    skills: ["Spear Phishing", "Header Analysis", "Domain Spoofing", "Credential Harvesting Defense"],
    completedPercentage: 80,
  },
  {
    id: "mod-8",
    slug: "networking-and-traffic-investigation",
    title: "Networking & Traffic Investigation",
    category: "Foundations",
    difficulty: "Easy",
    roomCount: 6,
    estimatedTime: "5 hours",
    description: "This module aims to introduce you to the ISO OSI and TCP/IP models and present all the main protocols necessary for networks to function, followed by live PCAP analysis using Wireshark.",
    iconType: "networking",
    badgeColor: {
      bg: "bg-indigo-950/40",
      border: "border-indigo-500/30",
      iconColor: "text-indigo-400",
      glow: "from-indigo-600/20 to-blue-500/10",
    },
    skills: ["TCP/IP", "Wireshark PCAP", "DNS Exfiltration", "Network Sniffing"],
    completedPercentage: 10,
  },
  {
    id: "mod-9",
    slug: "cryptography-and-credential-security",
    title: "Cryptography & Credential Security",
    category: "Foundations",
    difficulty: "Medium",
    roomCount: 5,
    estimatedTime: "4.5 hours",
    description: "Explore encryption algorithms, password hashing mechanisms, Kerberos authentication, and defenses against modern credential dumping and brute-force attacks.",
    iconType: "crypto",
    badgeColor: {
      bg: "bg-yellow-950/40",
      border: "border-yellow-500/30",
      iconColor: "text-yellow-400",
      glow: "from-yellow-600/20 to-amber-500/10",
    },
    skills: ["Hashing & Salting", "MFA / FIDO2", "Token Security", "Pass-the-Hash Defense"],
    completedPercentage: 0,
  },
  {
    id: "mod-10",
    slug: "malware-analysis-fundamentals",
    title: "Malware Analysis Fundamentals",
    category: "Forensics",
    difficulty: "Hard",
    roomCount: 6,
    estimatedTime: "6 hours",
    description: "Dive into static and dynamic malware analysis techniques. Dissect malicious PE binaries, inspect obfuscated scripts, evaluate sandbox detonations, and extract indicators of compromise (IOCs).",
    iconType: "malware",
    badgeColor: {
      bg: "bg-fuchsia-950/40",
      border: "border-fuchsia-500/30",
      iconColor: "text-fuchsia-400",
      glow: "from-fuchsia-600/20 to-pink-500/10",
    },
    skills: ["Static Analysis", "Dynamic Sandboxing", "YARA Rules", "Obfuscation Deobfuscation"],
    completedPercentage: 0,
  },
  {
    id: "mod-11",
    slug: "cloud-and-api-defense",
    title: "Cloud & API Security Defense",
    category: "Defensive",
    difficulty: "Medium",
    roomCount: 5,
    estimatedTime: "4 hours",
    description: "Discover common misconfigurations in cloud infrastructure, IAM permissions creep, API key leakages, and practical ways to harden cloud workloads and serverless environments.",
    iconType: "cloud",
    badgeColor: {
      bg: "bg-sky-950/40",
      border: "border-sky-500/30",
      iconColor: "text-sky-400",
      glow: "from-sky-600/20 to-cyan-500/10",
    },
    skills: ["Cloud IAM", "API Security", "Container Hardening", "Secrets Management"],
    completedPercentage: 0,
  },
  {
    id: "mod-12",
    slug: "threat-hunting-and-adversary-emulation",
    title: "Threat Hunting & Adversary Emulation",
    category: "Defensive",
    difficulty: "Hard",
    roomCount: 7,
    estimatedTime: "6.5 hours",
    description: "Proactively search through networks to detect and isolate advanced threats that evade existing security solutions. Utilize Sigma rules, Sysmon telemetry, and threat intelligence feeds.",
    iconType: "hunting",
    badgeColor: {
      bg: "bg-teal-950/40",
      border: "border-teal-500/30",
      iconColor: "text-teal-400",
      glow: "from-teal-600/20 to-emerald-500/10",
    },
    skills: ["Sysmon Logging", "Sigma Rules", "Hypothesis-Driven Hunting", "Adversary TTPs"],
    completedPercentage: 0,
  },
]
